AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  HandyHub

  DynamoDB tables and function for DynamoDB stream

Resources:
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: confirmation.lambda_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBOrders.StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON

  DynamoDBOrders:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: OrderID
          AttributeType: S
      KeySchema: 
        - AttributeName: OrderID
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DynamoDBServices:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: ServiceID
          AttributeType: S
      KeySchema: 
        - AttributeName: ServiceID
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1